# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Setup.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_Setup(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 572)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 727, 497))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page0)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_13 = QtWidgets.QFrame(self.page0)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.HaveDb_radioButton = QtWidgets.QRadioButton(self.frame_13)
        self.HaveDb_radioButton.setObjectName("HaveDb_radioButton")
        self.verticalLayout_16.addWidget(self.HaveDb_radioButton)
        self.NewDb_radioButton = QtWidgets.QRadioButton(self.frame_13)
        self.NewDb_radioButton.setObjectName("NewDb_radioButton")
        self.verticalLayout_16.addWidget(self.NewDb_radioButton)
        self.verticalLayout_12.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(self.page0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Page0_pushButton_next = QtWidgets.QPushButton(self.frame_12)
        self.Page0_pushButton_next.setObjectName("Page0_pushButton_next")
        self.horizontalLayout_6.addWidget(self.Page0_pushButton_next)
        self.Page0comboBoxSelectDbType = QtWidgets.QComboBox(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Page0comboBoxSelectDbType.sizePolicy().hasHeightForWidth())
        self.Page0comboBoxSelectDbType.setSizePolicy(sizePolicy)
        self.Page0comboBoxSelectDbType.setObjectName("Page0comboBoxSelectDbType")
        self.Page0comboBoxSelectDbType.addItem("")
        self.Page0comboBoxSelectDbType.setItemText(0, "")
        self.Page0comboBoxSelectDbType.addItem("")
        self.Page0comboBoxSelectDbType.addItem("")
        self.horizontalLayout_6.addWidget(self.Page0comboBoxSelectDbType)
        self.label_2 = QtWidgets.QLabel(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.verticalLayout_12.addWidget(self.frame_12, 0, QtCore.Qt.AlignRight)
        self.frame_8 = QtWidgets.QFrame(self.page0)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page0)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_9 = QtWidgets.QFrame(self.page1)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label = QtWidgets.QLabel(self.frame_9)
        self.label.setObjectName("label")
        self.verticalLayout_15.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.frame1_lineEdit_localhost_HaveDb = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1_lineEdit_localhost_HaveDb.sizePolicy().hasHeightForWidth())
        self.frame1_lineEdit_localhost_HaveDb.setSizePolicy(sizePolicy)
        self.frame1_lineEdit_localhost_HaveDb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame1_lineEdit_localhost_HaveDb.setMaxLength(50)
        self.frame1_lineEdit_localhost_HaveDb.setClearButtonEnabled(False)
        self.frame1_lineEdit_localhost_HaveDb.setObjectName("frame1_lineEdit_localhost_HaveDb")
        self.verticalLayout_15.addWidget(self.frame1_lineEdit_localhost_HaveDb)
        self.frame1_lineEdit_username_HaveDb = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1_lineEdit_username_HaveDb.sizePolicy().hasHeightForWidth())
        self.frame1_lineEdit_username_HaveDb.setSizePolicy(sizePolicy)
        self.frame1_lineEdit_username_HaveDb.setMaxLength(20)
        self.frame1_lineEdit_username_HaveDb.setClearButtonEnabled(False)
        self.frame1_lineEdit_username_HaveDb.setObjectName("frame1_lineEdit_username_HaveDb")
        self.verticalLayout_15.addWidget(self.frame1_lineEdit_username_HaveDb)
        self.frame1_lineEdit_password_HaveDb = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1_lineEdit_password_HaveDb.sizePolicy().hasHeightForWidth())
        self.frame1_lineEdit_password_HaveDb.setSizePolicy(sizePolicy)
        self.frame1_lineEdit_password_HaveDb.setMaxLength(20)
        self.frame1_lineEdit_password_HaveDb.setClearButtonEnabled(False)
        self.frame1_lineEdit_password_HaveDb.setObjectName("frame1_lineEdit_password_HaveDb")
        self.verticalLayout_15.addWidget(self.frame1_lineEdit_password_HaveDb)
        self.frame1_lineEdit_databaseName_HaveDb = QtWidgets.QLineEdit(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1_lineEdit_databaseName_HaveDb.sizePolicy().hasHeightForWidth())
        self.frame1_lineEdit_databaseName_HaveDb.setSizePolicy(sizePolicy)
        self.frame1_lineEdit_databaseName_HaveDb.setMaxLength(20)
        self.frame1_lineEdit_databaseName_HaveDb.setClearButtonEnabled(False)
        self.frame1_lineEdit_databaseName_HaveDb.setObjectName("frame1_lineEdit_databaseName_HaveDb")
        self.verticalLayout_15.addWidget(self.frame1_lineEdit_databaseName_HaveDb)
        self.StatusMsgCheckDbHave = QtWidgets.QLabel(self.frame_9)
        self.StatusMsgCheckDbHave.setText("")
        self.StatusMsgCheckDbHave.setObjectName("StatusMsgCheckDbHave")
        self.verticalLayout_15.addWidget(self.StatusMsgCheckDbHave, 0, QtCore.Qt.AlignHCenter)
        self.frame_14 = QtWidgets.QFrame(self.frame_9)
        self.frame_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButtonNextToSelectdbMySQL_Have = QtWidgets.QPushButton(self.frame_14)
        self.pushButtonNextToSelectdbMySQL_Have.setObjectName("pushButtonNextToSelectdbMySQL_Have")
        self.horizontalLayout_9.addWidget(self.pushButtonNextToSelectdbMySQL_Have)
        self.pushButtonBackToSelectdbMySQL_Have = QtWidgets.QPushButton(self.frame_14)
        self.pushButtonBackToSelectdbMySQL_Have.setObjectName("pushButtonBackToSelectdbMySQL_Have")
        self.horizontalLayout_9.addWidget(self.pushButtonBackToSelectdbMySQL_Have)
        self.verticalLayout_15.addWidget(self.frame_14)
        self.verticalLayout_14.addWidget(self.frame_9)
        self.frame_5 = QtWidgets.QFrame(self.page1)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_3 = QtWidgets.QToolButton(self.frame_10)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_4.addWidget(self.toolButton_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.verticalLayout_21.addWidget(self.frame_10)
        self.labelCheckDbSQLite = QtWidgets.QLabel(self.frame_5)
        self.labelCheckDbSQLite.setText("")
        self.labelCheckDbSQLite.setObjectName("labelCheckDbSQLite")
        self.verticalLayout_21.addWidget(self.labelCheckDbSQLite, 0, QtCore.Qt.AlignHCenter)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButtonNextToSelectdbSQLite = QtWidgets.QPushButton(self.frame_6)
        self.pushButtonNextToSelectdbSQLite.setObjectName("pushButtonNextToSelectdbSQLite")
        self.horizontalLayout_8.addWidget(self.pushButtonNextToSelectdbSQLite)
        self.pushButtonBackToSelectdbSQLite = QtWidgets.QPushButton(self.frame_6)
        self.pushButtonBackToSelectdbSQLite.setObjectName("pushButtonBackToSelectdbSQLite")
        self.horizontalLayout_8.addWidget(self.pushButtonBackToSelectdbSQLite)
        self.verticalLayout_21.addWidget(self.frame_6)
        self.verticalLayout_14.addWidget(self.frame_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame = QtWidgets.QFrame(self.page2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.InputInfoDb = QtWidgets.QLabel(self.frame)
        self.InputInfoDb.setAlignment(QtCore.Qt.AlignCenter)
        self.InputInfoDb.setObjectName("InputInfoDb")
        self.verticalLayout_3.addWidget(self.InputInfoDb)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SeletedNameDb = QtWidgets.QLabel(self.frame_7)
        self.SeletedNameDb.setText("")
        self.SeletedNameDb.setObjectName("SeletedNameDb")
        self.horizontalLayout_3.addWidget(self.SeletedNameDb)
        self.line_4 = QtWidgets.QFrame(self.frame_7)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_3.addWidget(self.line_4)
        self.LabelCreatedatabase = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelCreatedatabase.sizePolicy().hasHeightForWidth())
        self.LabelCreatedatabase.setSizePolicy(sizePolicy)
        self.LabelCreatedatabase.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelCreatedatabase.setObjectName("LabelCreatedatabase")
        self.horizontalLayout_3.addWidget(self.LabelCreatedatabase)
        self.verticalLayout_3.addWidget(self.frame_7, 0, QtCore.Qt.AlignHCenter)
        self.frame1_lineEdit_localhost = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1_lineEdit_localhost.sizePolicy().hasHeightForWidth())
        self.frame1_lineEdit_localhost.setSizePolicy(sizePolicy)
        self.frame1_lineEdit_localhost.setMaxLength(50)
        self.frame1_lineEdit_localhost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame1_lineEdit_localhost.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.frame1_lineEdit_localhost.setClearButtonEnabled(False)
        self.frame1_lineEdit_localhost.setObjectName("frame1_lineEdit_localhost")
        self.verticalLayout_3.addWidget(self.frame1_lineEdit_localhost)
        self.frame1_lineEdit_username = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1_lineEdit_username.sizePolicy().hasHeightForWidth())
        self.frame1_lineEdit_username.setSizePolicy(sizePolicy)
        self.frame1_lineEdit_username.setMaxLength(20)
        self.frame1_lineEdit_username.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame1_lineEdit_username.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.frame1_lineEdit_username.setClearButtonEnabled(False)
        self.frame1_lineEdit_username.setObjectName("frame1_lineEdit_username")
        self.verticalLayout_3.addWidget(self.frame1_lineEdit_username)
        self.frame1_lineEdit_password = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1_lineEdit_password.sizePolicy().hasHeightForWidth())
        self.frame1_lineEdit_password.setSizePolicy(sizePolicy)
        self.frame1_lineEdit_password.setMaxLength(20)
        self.frame1_lineEdit_password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame1_lineEdit_password.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.frame1_lineEdit_password.setClearButtonEnabled(False)
        self.frame1_lineEdit_password.setObjectName("frame1_lineEdit_password")
        self.verticalLayout_3.addWidget(self.frame1_lineEdit_password)
        self.frame1_lineEdit_databaseName = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame1_lineEdit_databaseName.sizePolicy().hasHeightForWidth())
        self.frame1_lineEdit_databaseName.setSizePolicy(sizePolicy)
        self.frame1_lineEdit_databaseName.setMaxLength(20)
        self.frame1_lineEdit_databaseName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame1_lineEdit_databaseName.setClearButtonEnabled(False)
        self.frame1_lineEdit_databaseName.setObjectName("frame1_lineEdit_databaseName")
        self.verticalLayout_3.addWidget(self.frame1_lineEdit_databaseName)
        self.Label_ErrorConnection = QtWidgets.QLabel(self.frame)
        self.Label_ErrorConnection.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_ErrorConnection.setObjectName("Label_ErrorConnection")
        self.verticalLayout_3.addWidget(self.Label_ErrorConnection)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.page2_pushButton_next = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page2_pushButton_next.sizePolicy().hasHeightForWidth())
        self.page2_pushButton_next.setSizePolicy(sizePolicy)
        self.page2_pushButton_next.setObjectName("page2_pushButton_next")
        self.horizontalLayout_5.addWidget(self.page2_pushButton_next)
        self.page2_pushButton_back = QtWidgets.QPushButton(self.frame_11)
        self.page2_pushButton_back.setObjectName("page2_pushButton_back")
        self.horizontalLayout_5.addWidget(self.page2_pushButton_back)
        self.verticalLayout_3.addWidget(self.frame_11)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.verticalLayout_9.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_2 = QtWidgets.QFrame(self.page3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame2_label_createAdmin = QtWidgets.QLabel(self.frame_2)
        self.frame2_label_createAdmin.setAlignment(QtCore.Qt.AlignCenter)
        self.frame2_label_createAdmin.setObjectName("frame2_label_createAdmin")
        self.verticalLayout_4.addWidget(self.frame2_label_createAdmin)
        self.Page3LineEdit_Username = QtWidgets.QLineEdit(self.frame_2)
        self.Page3LineEdit_Username.setMaxLength(30)
        self.Page3LineEdit_Username.setClearButtonEnabled(False)
        self.Page3LineEdit_Username.setObjectName("Page3LineEdit_Username")
        self.verticalLayout_4.addWidget(self.Page3LineEdit_Username)
        self.Page3LineEdit_Pass = QtWidgets.QLineEdit(self.frame_2)
        self.Page3LineEdit_Pass.setMaxLength(30)
        self.Page3LineEdit_Pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Page3LineEdit_Pass.setClearButtonEnabled(False)
        self.Page3LineEdit_Pass.setObjectName("Page3LineEdit_Pass")
        self.verticalLayout_4.addWidget(self.Page3LineEdit_Pass)
        self.Page3LineEdit_RplyPass = QtWidgets.QLineEdit(self.frame_2)
        self.Page3LineEdit_RplyPass.setMaxLength(30)
        self.Page3LineEdit_RplyPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Page3LineEdit_RplyPass.setClearButtonEnabled(False)
        self.Page3LineEdit_RplyPass.setObjectName("Page3LineEdit_RplyPass")
        self.verticalLayout_4.addWidget(self.Page3LineEdit_RplyPass)
        self.Page3_comboBoxSecurityQuestion = QtWidgets.QComboBox(self.frame_2)
        self.Page3_comboBoxSecurityQuestion.setObjectName("Page3_comboBoxSecurityQuestion")
        self.Page3_comboBoxSecurityQuestion.addItem("")
        self.Page3_comboBoxSecurityQuestion.addItem("")
        self.Page3_comboBoxSecurityQuestion.addItem("")
        self.Page3_comboBoxSecurityQuestion.addItem("")
        self.Page3_comboBoxSecurityQuestion.addItem("")
        self.verticalLayout_4.addWidget(self.Page3_comboBoxSecurityQuestion)
        self.Page3LineEdit_SecurityAnswer = QtWidgets.QLineEdit(self.frame_2)
        self.Page3LineEdit_SecurityAnswer.setMaxLength(30)
        self.Page3LineEdit_SecurityAnswer.setObjectName("Page3LineEdit_SecurityAnswer")
        self.verticalLayout_4.addWidget(self.Page3LineEdit_SecurityAnswer)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.page3_pushButton_next = QtWidgets.QPushButton(self.frame_4)
        self.page3_pushButton_next.setObjectName("page3_pushButton_next")
        self.horizontalLayout.addWidget(self.page3_pushButton_next)
        self.page3_pushButton_back = QtWidgets.QPushButton(self.frame_4)
        self.page3_pushButton_back.setObjectName("page3_pushButton_back")
        self.horizontalLayout.addWidget(self.page3_pushButton_back)
        self.verticalLayout_4.addWidget(self.frame_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.verticalLayout_10.addWidget(self.frame_2)
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_3 = QtWidgets.QFrame(self.page4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame3_lineEdit_username = QtWidgets.QLineEdit(self.frame_3)
        self.frame3_lineEdit_username.setMaxLength(30)
        self.frame3_lineEdit_username.setClearButtonEnabled(False)
        self.frame3_lineEdit_username.setObjectName("frame3_lineEdit_username")
        self.verticalLayout_5.addWidget(self.frame3_lineEdit_username)
        self.frame3_lineEdit_pass = QtWidgets.QLineEdit(self.frame_3)
        self.frame3_lineEdit_pass.setMaxLength(30)
        self.frame3_lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.frame3_lineEdit_pass.setClearButtonEnabled(False)
        self.frame3_lineEdit_pass.setObjectName("frame3_lineEdit_pass")
        self.verticalLayout_5.addWidget(self.frame3_lineEdit_pass)
        self.ForeGetlabel = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ForeGetlabel.sizePolicy().hasHeightForWidth())
        self.ForeGetlabel.setSizePolicy(sizePolicy)
        self.ForeGetlabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ForeGetlabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.ForeGetlabel.setObjectName("ForeGetlabel")
        self.verticalLayout_5.addWidget(self.ForeGetlabel)
        self.ErrorNameOrPassword = QtWidgets.QLabel(self.frame_3)
        self.ErrorNameOrPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.ErrorNameOrPassword.setObjectName("ErrorNameOrPassword")
        self.verticalLayout_5.addWidget(self.ErrorNameOrPassword)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.moreIfJoin = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moreIfJoin.sizePolicy().hasHeightForWidth())
        self.moreIfJoin.setSizePolicy(sizePolicy)
        self.moreIfJoin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.moreIfJoin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.moreIfJoin.setObjectName("moreIfJoin")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.moreIfJoin)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.countErrorJoin = QtWidgets.QLabel(self.moreIfJoin)
        self.countErrorJoin.setObjectName("countErrorJoin")
        self.horizontalLayout_2.addWidget(self.countErrorJoin)
        self.line_3 = QtWidgets.QFrame(self.moreIfJoin)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.label_3 = QtWidgets.QLabel(self.moreIfJoin)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_5.addWidget(self.moreIfJoin, 0, QtCore.Qt.AlignHCenter)
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.LoginJoinStander = QtWidgets.QPushButton(self.frame_3)
        self.LoginJoinStander.setObjectName("LoginJoinStander")
        self.verticalLayout_5.addWidget(self.LoginJoinStander)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.verticalLayout_11.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FreamRestUserQuetion = QtWidgets.QFrame(self.page5)
        self.FreamRestUserQuetion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FreamRestUserQuetion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FreamRestUserQuetion.setObjectName("FreamRestUserQuetion")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.FreamRestUserQuetion)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_RestQuetionAndAnswers = QtWidgets.QFrame(self.FreamRestUserQuetion)
        self.frame_RestQuetionAndAnswers.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_RestQuetionAndAnswers.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_RestQuetionAndAnswers.setObjectName("frame_RestQuetionAndAnswers")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_RestQuetionAndAnswers)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.checkBoxRestQuetion_Answer_Secruty = QtWidgets.QCheckBox(self.frame_RestQuetionAndAnswers)
        self.checkBoxRestQuetion_Answer_Secruty.setObjectName("checkBoxRestQuetion_Answer_Secruty")
        self.verticalLayout_20.addWidget(self.checkBoxRestQuetion_Answer_Secruty)
        self.verticalLayout_6.addWidget(self.frame_RestQuetionAndAnswers)
        self.frame_Quetion_Answers_Join = QtWidgets.QFrame(self.FreamRestUserQuetion)
        self.frame_Quetion_Answers_Join.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Quetion_Answers_Join.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Quetion_Answers_Join.setObjectName("frame_Quetion_Answers_Join")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_Quetion_Answers_Join)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.forgot_quetionsecurty_comboBox = QtWidgets.QComboBox(self.frame_Quetion_Answers_Join)
        self.forgot_quetionsecurty_comboBox.setObjectName("forgot_quetionsecurty_comboBox")
        self.forgot_quetionsecurty_comboBox.addItem("")
        self.forgot_quetionsecurty_comboBox.addItem("")
        self.forgot_quetionsecurty_comboBox.addItem("")
        self.forgot_quetionsecurty_comboBox.addItem("")
        self.forgot_quetionsecurty_comboBox.addItem("")
        self.verticalLayout_18.addWidget(self.forgot_quetionsecurty_comboBox)
        self.forgot_answersecurty_lineEdit = QtWidgets.QLineEdit(self.frame_Quetion_Answers_Join)
        self.forgot_answersecurty_lineEdit.setObjectName("forgot_answersecurty_lineEdit")
        self.verticalLayout_18.addWidget(self.forgot_answersecurty_lineEdit)
        self.verticalLayout_6.addWidget(self.frame_Quetion_Answers_Join)
        self.frame_Forgot_Errorquetion = QtWidgets.QFrame(self.FreamRestUserQuetion)
        self.frame_Forgot_Errorquetion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Forgot_Errorquetion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Forgot_Errorquetion.setObjectName("frame_Forgot_Errorquetion")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_Forgot_Errorquetion)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.ErrorNameOrPassword_2 = QtWidgets.QLabel(self.frame_Forgot_Errorquetion)
        self.ErrorNameOrPassword_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ErrorNameOrPassword_2.setObjectName("ErrorNameOrPassword_2")
        self.verticalLayout_17.addWidget(self.ErrorNameOrPassword_2)
        self.line_6 = QtWidgets.QFrame(self.frame_Forgot_Errorquetion)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_17.addWidget(self.line_6)
        self.moreIfJoin_2 = QtWidgets.QFrame(self.frame_Forgot_Errorquetion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moreIfJoin_2.sizePolicy().hasHeightForWidth())
        self.moreIfJoin_2.setSizePolicy(sizePolicy)
        self.moreIfJoin_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.moreIfJoin_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.moreIfJoin_2.setObjectName("moreIfJoin_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.moreIfJoin_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.countErrorJoin_2 = QtWidgets.QLabel(self.moreIfJoin_2)
        self.countErrorJoin_2.setObjectName("countErrorJoin_2")
        self.horizontalLayout_7.addWidget(self.countErrorJoin_2)
        self.line_5 = QtWidgets.QFrame(self.moreIfJoin_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_7.addWidget(self.line_5)
        self.label_4 = QtWidgets.QLabel(self.moreIfJoin_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.verticalLayout_17.addWidget(self.moreIfJoin_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.frame_Forgot_Errorquetion)
        self.frame_Quetion_Answers_Join_2 = QtWidgets.QFrame(self.FreamRestUserQuetion)
        self.frame_Quetion_Answers_Join_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Quetion_Answers_Join_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Quetion_Answers_Join_2.setObjectName("frame_Quetion_Answers_Join_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_Quetion_Answers_Join_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.forgot_pushButton_join = QtWidgets.QPushButton(self.frame_Quetion_Answers_Join_2)
        self.forgot_pushButton_join.setObjectName("forgot_pushButton_join")
        self.verticalLayout_19.addWidget(self.forgot_pushButton_join)
        self.verticalLayout_6.addWidget(self.frame_Quetion_Answers_Join_2)
        self.FrameRestPass = QtWidgets.QFrame(self.FreamRestUserQuetion)
        self.FrameRestPass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameRestPass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameRestPass.setObjectName("FrameRestPass")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.FrameRestPass)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.forgot_newpassword = QtWidgets.QLineEdit(self.FrameRestPass)
        self.forgot_newpassword.setMaxLength(30)
        self.forgot_newpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.forgot_newpassword.setObjectName("forgot_newpassword")
        self.verticalLayout_8.addWidget(self.forgot_newpassword)
        self.forgot_RetypePassword = QtWidgets.QLineEdit(self.FrameRestPass)
        self.forgot_RetypePassword.setMaxLength(30)
        self.forgot_RetypePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.forgot_RetypePassword.setClearButtonEnabled(False)
        self.forgot_RetypePassword.setObjectName("forgot_RetypePassword")
        self.verticalLayout_8.addWidget(self.forgot_RetypePassword)
        self.forgot_pushButton_Save = QtWidgets.QPushButton(self.FrameRestPass)
        self.forgot_pushButton_Save.setObjectName("forgot_pushButton_Save")
        self.verticalLayout_8.addWidget(self.forgot_pushButton_Save)
        self.verticalLayout_6.addWidget(self.FrameRestPass)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.FreamRestUserQuetion)
        self.stackedWidget.addWidget(self.page5)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HaveDb_radioButton.setText(_translate("MainWindow", "قاعدة بيانات حالية"))
        self.NewDb_radioButton.setText(_translate("MainWindow", "قاعدة بيانات جديدة"))
        self.Page0_pushButton_next.setText(_translate("MainWindow", "التالي"))
        self.Page0comboBoxSelectDbType.setItemText(1, _translate("MainWindow", "MySQL"))
        self.Page0comboBoxSelectDbType.setItemText(2, _translate("MainWindow", "SQLite"))
        self.label_2.setText(_translate("MainWindow", "نوع قواعد البيانات"))
        self.label.setText(_translate("MainWindow", "ادخل معلومات الاتصال بقواعد البيانات واسم قاعدة البيانات المراد ربطها"))
        self.frame1_lineEdit_localhost_HaveDb.setPlaceholderText(_translate("MainWindow", "عنوان السيرفر     localhost"))
        self.frame1_lineEdit_username_HaveDb.setPlaceholderText(_translate("MainWindow", "اسم المستخدم لقاعدة البيانات "))
        self.frame1_lineEdit_password_HaveDb.setPlaceholderText(_translate("MainWindow", "كلمة المرور لقاعدة البيانات "))
        self.frame1_lineEdit_databaseName_HaveDb.setPlaceholderText(_translate("MainWindow", "اسم قاعدة البيانات"))
        self.pushButtonNextToSelectdbMySQL_Have.setText(_translate("MainWindow", "التالي"))
        self.pushButtonBackToSelectdbMySQL_Have.setText(_translate("MainWindow", "رجوع"))
        self.toolButton_3.setText(_translate("MainWindow", "اختار ..."))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "اختر قاعدة البيانات المحلية"))
        self.pushButtonNextToSelectdbSQLite.setText(_translate("MainWindow", "التالي"))
        self.pushButtonBackToSelectdbSQLite.setText(_translate("MainWindow", "رجوع"))
        self.InputInfoDb.setText(_translate("MainWindow", "ادخل معلومات الاتصال بقواعد البيانات "))
        self.LabelCreatedatabase.setText(_translate("MainWindow", "انشاء قاعدة بيانات جديدة "))
        self.frame1_lineEdit_localhost.setPlaceholderText(_translate("MainWindow", "   عنونا السيرفر locolhost"))
        self.frame1_lineEdit_username.setPlaceholderText(_translate("MainWindow", "اسم المستخدم لقاعدة البيانات "))
        self.frame1_lineEdit_password.setPlaceholderText(_translate("MainWindow", "كلمة المرور لقاعدة البيانات "))
        self.frame1_lineEdit_databaseName.setPlaceholderText(_translate("MainWindow", "اسم قاعدة البيانات"))
        self.Label_ErrorConnection.setText(_translate("MainWindow", "فشل الاتصال"))
        self.page2_pushButton_next.setText(_translate("MainWindow", "التالي"))
        self.page2_pushButton_back.setText(_translate("MainWindow", "رجوع"))
        self.frame2_label_createAdmin.setText(_translate("MainWindow", "انشاء اسم المستخدم وكلمة المرور"))
        self.Page3LineEdit_Username.setPlaceholderText(_translate("MainWindow", "اسم المستخدم"))
        self.Page3LineEdit_Pass.setPlaceholderText(_translate("MainWindow", "كلمة المرور"))
        self.Page3LineEdit_RplyPass.setPlaceholderText(_translate("MainWindow", "إعادة كلمة المرور"))
        self.Page3_comboBoxSecurityQuestion.setItemText(0, _translate("MainWindow", "ما هو اسم اول مدرسة لك ؟"))
        self.Page3_comboBoxSecurityQuestion.setItemText(1, _translate("MainWindow", "من الشخصية الموثرة لك ؟"))
        self.Page3_comboBoxSecurityQuestion.setItemText(2, _translate("MainWindow", "ماهو اسم الصديق المفضل لك ؟"))
        self.Page3_comboBoxSecurityQuestion.setItemText(3, _translate("MainWindow", "ماهو البلد المفضل لك ؟"))
        self.Page3_comboBoxSecurityQuestion.setItemText(4, _translate("MainWindow", "ماهو اسم الفلم المفضل لك ؟"))
        self.Page3LineEdit_SecurityAnswer.setPlaceholderText(_translate("MainWindow", "جواب السؤال"))
        self.page3_pushButton_next.setText(_translate("MainWindow", "التالي"))
        self.page3_pushButton_back.setText(_translate("MainWindow", "رجوع"))
        self.frame3_lineEdit_username.setPlaceholderText(_translate("MainWindow", "اسم المستخدم"))
        self.frame3_lineEdit_pass.setPlaceholderText(_translate("MainWindow", "كلمة المرور"))
        self.ForeGetlabel.setText(_translate("MainWindow", "نسيت كلمة المرور"))
        self.ErrorNameOrPassword.setText(_translate("MainWindow", "اسم المستخدم | كلمة المرور خطاء"))
        self.countErrorJoin.setText(_translate("MainWindow", "عدد المحاولات الخاطئه"))
        self.label_3.setText(_translate("MainWindow", "لديك 5 محاولات"))
        self.LoginJoinStander.setText(_translate("MainWindow", "دخول"))
        self.checkBoxRestQuetion_Answer_Secruty.setText(_translate("MainWindow", "هل تريد تغير سؤال الامان"))
        self.forgot_quetionsecurty_comboBox.setItemText(0, _translate("MainWindow", "ما هو اسم اول مدرسة لك ؟"))
        self.forgot_quetionsecurty_comboBox.setItemText(1, _translate("MainWindow", "من الشخصية الموثرة لك ؟"))
        self.forgot_quetionsecurty_comboBox.setItemText(2, _translate("MainWindow", "ماهو اسم الصديق المفضل لك ؟"))
        self.forgot_quetionsecurty_comboBox.setItemText(3, _translate("MainWindow", "ماهو البلد المفضل لك ؟"))
        self.forgot_quetionsecurty_comboBox.setItemText(4, _translate("MainWindow", "ماهو اسم الفلم المفضل لك ؟"))
        self.forgot_answersecurty_lineEdit.setPlaceholderText(_translate("MainWindow", "جواب السؤال"))
        self.ErrorNameOrPassword_2.setText(_translate("MainWindow", "سؤال الامان | الجواب على سؤال الامان .. خطاء"))
        self.countErrorJoin_2.setText(_translate("MainWindow", "عدد المحاولات الخاطئه"))
        self.label_4.setText(_translate("MainWindow", "لديك 5 محاولات"))
        self.forgot_pushButton_join.setText(_translate("MainWindow", "دخول"))
        self.forgot_newpassword.setPlaceholderText(_translate("MainWindow", "كلمة المرور الجديدة"))
        self.forgot_RetypePassword.setPlaceholderText(_translate("MainWindow", "إعادة كتابة كلمة المرور"))
        self.forgot_pushButton_Save.setText(_translate("MainWindow", "حفظ"))

